AWSTemplateFormatVersion: '2010-09-09'
Description: Bastion Host
Metadata:
  ParameterGroups:
  - Label:
      default: Network Configuration
    Parameters:
    - VPCID
    - PublicSubnet1ID
    - PublicSubnet2ID
    - RemoteAccessCIDR
  - Label:
      default: Amazon EC2 Configuration
    Parameters:
    - KeyPairName
    - BastionInstanceType
    - WindowsOrLinux
  ParameterLabels:
    BastionInstanceType:
      default: Bastion Instance Type
    KeyPairName:
      default: Key Pair Name
    PublicSubnet1ID:
      default: Public Subnet 1 ID
    PublicSubnet2ID:
      default: Public Subnet 2 ID
    RemoteAccessCIDR:
      default: Allowed Bastion External Access CIDR
    VPCID:
      default: VPC ID
    WindowsorLinux:
      default: Windows or Linux Bastion

Parameters:
  BastionInstanceType:
    AllowedValues:
    - t2.large
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    Default: t2.large
    Description: Amazon EC2 instance type for the bastion instances
    Type: String
  KeyPairName:
    Description: Enter a Public/private key pair. If you do not have one in this region,
      please create it before continuing
    Type: AWS::EC2::KeyPair::KeyName
  PublicSubnet1ID:
    Description: ID of the public subnet 1 that you want to provision the first bastion
      into (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: ID of the public subnet 2 you want to provision the second bastion
      into (e.g., subnet-e3246d8e)
    Type: AWS::EC2::Subnet::Id
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-tableau-server-healthcare/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
  WindowsBastionPwd:
    Description: Password for the administrative account. Must be at least 8 characters containing letters, numbers and symbols. If using Windows, min length should be 8.
    Type: String
    Default: ""
    MaxLength: 32
    NoEcho: true
  WindowsBastionAdmin:
    Description: User name for the new local administrator account. If you are using Windows, min length should be 5.
    Type: String
    Default: ""
    MaxLength: 25
    AllowedPattern: "[a-zA-Z0-9]*"
  WindowsOrLinux:
    AllowedValues:
    - linux
    - windows
    Description: Whether to launch a Windows or Linux bastion
    Type: String

Conditions:
  IsWindows: !Equals [ !Ref WindowsOrLinux, windows ]
  IsLinux: !Not [ Condition: IsWindows ]

Resources:
  BastionHostWindows:
    Type: AWS::CloudFormation::Stack
    Condition: IsWindows
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-rdgateway/templates/rdgw-standalone.template
      Parameters:
        AdminUser: !Ref WindowsBastionAdmin
        AdminPassword: !Ref WindowsBastionPwd
        KeyPairName: !Ref KeyPairName
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        RDGWCIDR: !Ref RemoteAccessCIDR
        RDGWInstanceType: !Ref BastionInstanceType
        VPCID: !Ref VPCID

  BastionHostLinux:
    Type: AWS::CloudFormation::Stack
    Condition: IsLinux
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template
      Parameters:
        BastionInstanceType: !Ref BastionInstanceType
        KeyPairName: !Ref KeyPairName
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        VPCID: !Ref VPCID

Outputs:
  BastionSecurityGroupID:
    Value: !If [ IsWindows, !GetAtt BastionHostWindows.Outputs.RemoteDesktopGatewaySGID, !GetAtt BastionHostLinux.Outputs.BastionSecurityGroupID ]
    Description: Bastion Host Security Group ID 
  BastionPublicIp:
    Value: !If [ IsWindows, !GetAtt BastionHostWindows.Outputs.EIP1, !GetAtt BastionHostLinux.Outputs.EIP1 ]

