AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for config rules

Parameters:
  LogBucketName:
    Type: String
    Description: Log bucket

Resources:
  # ConfigRole
  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - "config.amazonaws.com"
            Action:
              - "sts:AssumeRole"
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole

  ConfigRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ConfigRolePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          Resource: !Sub arn:aws:s3:::${LogBucket}/*
          Condition:
            StringLike:
              s3:x-amz-acl: bucket-owner-full-control
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
          - "config:Put*"
          Resource: "*"
      Roles:
      - !Ref ConfigRole

  LambdaConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSConfigRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
  #  Condition: NoConfigRecorder
    Properties:
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
      RoleARN: !GetAtt ConfigRole.Arn
  
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
  #  Condition: NoConfigDeliveryChannel
    Properties:
      S3BucketName: !Ref LogBucketName
      S3KeyPrefix: "config"

  #IAM Configuration Change Detected
  #CloudTrail log config change detected
  CloudTrailEnabled:
    Description: Checks whether AWS CloudTrail is enabled in your AWS account
    MaximumExecutionFrequency: One_Hour
    Scope:
      ComplianceResourceTypes:
      - AWS::CloudTrail::Trail
    Source:
      Owner: AWS
      SourceIdentifier: CLOUD_TRAIL_ENABLED
  #Config change detected

  TriggerConfigRecorderEnabled:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaConfigRecorderEnabled
      Principal: config.amazonaws.com
  RuleConfigRecorderEnabled:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigRecorder
    Properties:
      ConfigRuleName: ConfigRecorderEnabled
      Description: Checks if AWS Config recorder is turned on
      InputParameters:
        s3BucketName: !Ref LogBucketName
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: !Ref LambdaConfigRecorderEnabled
        SourceDetails:
        - EventSource: aws.config
          MaximumExecutionFrequency: One_Hour
          MessageType: ScheduledNotification
  LambdaConfigRecorderEnabled:
    Type: AWS::Lambda::Function
    Properties:
      Description: Checks if Config Recorder is enabled
      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt LambdaConfigRecorderRole
      Timeout: 30
      Code:
        ZipFile: | 
          import boto3
          import json
          from datetime import datetime
          config = boto3.client('config')
          def evaluate_compliance(rule_parameters):
              # First check configuration recorder is created
              config_recorder_response = config.describe_configuration_recorder_status()
              if 'ConfigurationRecordersStatus' not in config_recorder_response or \
                              len(config_recorder_response['ConfigurationRecordersStatus']) < 1:
                  return {
                      'compliance_type': 'NON_COMPLIANT',
                      'annotation': 'Cannot find config recorder status'
                  }
              for config_recorder in config_recorder_response['ConfigurationRecordersStatus']:
                  if not config_recorder['recording']:
                      return {
                          'compliance_type': 'NON_COMPLIANT',
                          'annotation': 'Config recorder is not recording'
                      }
              # Check that there are delivery channels and that they're mapping to the appropriate buckets
              delivery_channels_response = config.describe_delivery_channels()
              if 'DeliveryChannels' not in delivery_channels_response or len(delivery_channels_response['DeliveryChannels']) < 1:
                  return {
                      'compliance_type': 'NON_COMPLIANT',
                      'annotation': 'No delivery channel for config recorder'
                  }
              if 's3BucketName' in rule_parameters:
                  for channel in delivery_channels_response['DeliveryChannels']:
                      if channel['s3BucketName'] != rule_parameters['s3BucketName']:
                          return {
                              'compliance_type': 'NON_COMPLIANT',
                              'annotation': 'Config recorder writing to incorrect bucket'
                          }
              if 'snsTopicARN' in rule_parameters:
                  for channel in delivery_channels_response['DeliveryChannels']:
                      if channel['snsTopicARN'] != rule_parameters['snsTopicARN']:
                          return {
                              'compliance_type': 'NON_COMPLIANT',
                              'annotation': 'Config recording writing to incorrect SNS topic'
                          }
              return {
                  'compliance_type': 'COMPLIANT',
                  'annotation': 'Config recorder enabled with appropriate delivery channel'
              }
          def handler(event, context):
              today = datetime.today()
              rule_parameters = json.loads(event['ruleParameters'])
              evaluation = evaluate_compliance(rule_parameters)
              result_token = event['resultToken'] if 'resultToken' in event else 'No token found'
              config.put_evaluations(
                  Evaluations=[
                      {
                          'ComplianceResourceType': 'AWS::::Account',
                          'ComplianceResourceId': event['accountId'],
                          'ComplianceType': evaluation['compliance_type'],
                          'Annotation': evaluation['annotation'],
                          'OrderingTimestamp': datetime(today.year, today.month, today.day, today.hour)
                      }
                  ],
                  ResultToken=result_token
              )
          
  #ELB Config change detected
  ALBEncryption:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks to ensure that all application load balancers are only reachable via HTTPS endpoints and not HTTP
      MaximumExecutionFrequency:
      Scope:
      Source:
        Owner: CUSTOM_LAMBDA

  # EBS volume changes detected
  EBSVolumeEncryption:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks to ensure attached EBS volumes are encrypted
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: ENCRYPTED_VOLUMES

  S3BucketPublicReadProhibited:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks that your S3 buckets do not allow public read access. If an S3 bucket policy or bucket ACL allows public read access, the bucket is noncompliant.
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED

  S3BucketPublicWriteProhibited:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks that your S3 buckets do not allow public write access. If an S3 bucket policy or bucket ACL allows public write access, the bucket is noncompliant.
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED

  S3EncryptionEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      # N.B. May need to update this policy
      Description: Checks for explicit denies on put-object requests without server side encryption.
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED 

  S3VersioningEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks whether versioning is enabled for your S3 buckets
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED 
  #Update or delete of a security Group

  UnrestrictedSSH:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks whether security groups that are in use disallow unrestricted incoming SSH traffic
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED

  UnrestrictedPorts:
    Type: AWS::Config::ConfigRule
    Properties:
      Description: Checks whether security groups that are in use disallow unrestricted incoming TCP traffic to the specified ports.
      InputParameters:
        blockedPort1: 22
        blockedPort2: 443
        blockedPort3: 80
        blockedPort4: 3389
        blockedPort5: 8850
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC

Output:
  LogBucketName:
    Value: !If [ NoLogBucket, !Ref LogBucket, LogBucketName ]

