---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for basic logging functionality. Sets up ELB logging and Config if 
  the Config Recorder and Config Delivery Channel are not yet set up.

Parameters:
  ConfigRecorder:
    Type: String
    Default: ""
    Description: Config Recorder ARN. Empty string will create a new Config Recorder. 
      Will throw an error if you have a Config Recorder already created and leave this blank.
  ConfigDeliveryChannel:
    Type: String
    Default: ""
    Description: Config Delivery Channel. Must have if Config Recorder specified.
  QSTagKey:
    Type: String
    Description: Tag key to identify resources from this Quick Start
  QSTagValue:
    Type: String
    Description: Tag value to identify resources from this Quick Start

Mappings:
  ElbLogging:
    us-east-1: 
      Principal: '127311923021'
    us-east-2: 
      Principal: '033677994240'
    us-west-1: 
      Principal: '027434742980'
    us-west-2: 
      Principal: '797873946194'
    ca-central-1:
      Principal: '985666609251'
    eu-central-1:
      Principal: '054676820928'
    eu-west-1:
      Principal: '156460612806'
    eu-west-2:
      Principal: '652711504416'
    eu-west-3:
      Principal: '009996457667'
    ap-northeast-1:
      Principal: '582318560864'
    ap-northeast-2:
      Principal: '600734575887'
    ap-southeast-1:
      Principal: '114774131450'
    ap-southeast-2:
      Principal: '783225319266'
    ap-south-1:
      Principal: '718504428378'
    sa-east-1:
      Principal: '507241528517'

Conditions:
  CreateLogBucket: !Equals [ LogBucketName, '' ]
  CreateConfig: !And [ !Equals [ ConfigRecorder, '' ], !Equals [ ConfigDeliveryChannel, '' ] ]

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: !Ref QSTagKey
        Value: !Ref QSTagValue
      VersioningConfiguration:
        Status: Enabled
      
  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: DeleteObjectPolicy
        Statement:
        - Sid: DenyDeleteObject
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteObject"
          Resource: !Sub arn:aws:s3:::${LogBucket}/*
        - Sid: DenyDeleteBucket
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteBucket"
          Resource: !Sub arn:aws:s3:::${LogBucket}
        - Sid: ElbLogs
          Effect: Allow
          Principal:
            AWS:
            - !FindInMap [ ElbLogging, !Ref "AWS::Region" , Principal ]
          Action: "s3:PutObject"
          Resource: !Sub arn:aws:s3:::${LogBucket}/*

Outputs:
  LogBucket:
    Value: !Ref LogBucket
