---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for basic logging functionality



Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: DeleteObjectPolicy
        Statement:
        - Sid: DenyDeleteObject
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteObject"
          Resource: !Sub arn:aws:s3:::${LogBucket}/*
        - Sid: DenyDeleteBucket
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteBucket"
          Resource: !Sub arn:aws:s3:::${LogBucket}

  ConfigRecorderEnabled:
    Type: Custom::ConfigRecorderEnabled
    Properties:



  ConfigRecorderEnabledLambda:
    Type: AWS::Lambda::Function
    Properties:

      def lambda_handler(event, context)


  ConfigDeliveryChannelEnabled:
    Type: Custom::ConfigDeliveryChannelEnabled
    Properties:
      ServiceToken:
      VpcId: !Ref VpcId

  ConfigDeliveryChannelEnabledLambda:
    Type: AWS::Lambda::Function
    Properties:
      ServiceToken:

  ConfigRulesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/config-rules.yaml
      Parameters:
        LogBucket: !If [ NoLogBucket, !Ref LogBucket, LogBucketName ]

Output:
  LogBucketName:
    Value: !If [ NoLogBucket, !Ref LogBucket, LogBucketName ]