---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for basic logging functionality

Mappings:
  ElbLogging:
    us-east-1: 
      Principal: '127311923021'
    us-east-2: 
      Principal: '033677994240'
    us-west-1: 
      Principal: '027434742980'
    us-west-2: 
      Principal: '797873946194'
    ca-central-1:
      Principal: '985666609251'
    eu-central-1:
      Principal: '054676820928'
    eu-west-1:
      Principal: '156460612806'
    eu-west-2:
      Principal: '652711504416'
    eu-west-3:
      Principal: '009996457667'
    ap-northeast-1:
      Principal: '582318560864'
    ap-northeast-2:
      Principal: '600734575887'
    ap-southeast-1:
      Principal: '114774131450'
    ap-southeast-2:
      Principal: '783225319266'
    ap-south-1:
      Principal: '718504428378'
    sa-east-1:
      Principal: '507241528517'

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: DeleteObjectPolicy
        Statement:
        - Sid: DenyDeleteObject
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteObject"
          Resource: !Sub arn:aws:s3:::${LogBucket}/*
        - Sid: DenyDeleteBucket
          Effect: Deny
          Principal: "*"
          Action: "s3:DeleteBucket"
          Resource: !Sub arn:aws:s3:::${LogBucket}
        - Sid: ElbLogs
          Effect: Allow
          Principal:
            AWS:
            - !FindInMap [ ElbLogging, !Ref "AWS::Region" , Principal ]
          Action: "s3:PutObject"
          Resource: !Sub arn:aws:s3:::${LogBucket}/*


  #ConfigRecorderEnabled:
   # Type: Custom::ConfigRecorderEnabled
   # Properties:
  #ConfigRecorderEnabledLambda:
    #Type: AWS::Lambda::Function
    #Properties:

#      def lambda_handler(event, context)
#  ConfigDeliveryChannelEnabled:
#    Type: Custom::ConfigDeliveryChannelEnabled
#    Properties:
#      ServiceToken:
#      VpcId: !Ref VpcId

#  ConfigDeliveryChannelEnabledLambda:
#    Type: AWS::Lambda::Function
#    Properties:
#      ServiceToken:

#  ConfigRulesStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/config-rules.yaml
#      Parameters:
#        LogBucket: !If [ NoLogBucket, !Ref LogBucket, LogBucketName ]

Outputs:
  LogBucket:
    Value: !Ref LogBucket