AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS CloudFormation Template: Deploys infrastructure for Tableau Server"
Metadata:
  AWS::CloudFormation::Interface:
    ParamaterLabels:
      AMIOS:
        default: AMI Operating System
      AWSHostedZoneID:
        default: DNS Zone ID
      AWSPublicFQDN:
        default: Full DNS Name for Cluster
      AcceptEULA:
        default: Accept Tableau End User License Agreement
      IPAddress:
        default: EIP address for initial node
      InstanceType:
        default: Amazon EC2 instance type
      KeyPairName:
        default: Key Pair Name
      Password:
        default: Tableau Services Manager (TSM) administrator password
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      RegCity:
        default: City
      RegCompany:
        default: Company
      RegCountry:
        default: Country
      RegDepartment:
        default: Department
      RegEmail:
        default: Email Address
      RegFirstName:
        default: First Name
      RegIndustry:
        default: Industry
      RegLastName:
        default: Last Name
      RegPhone:
        default: Phone
      RegState:
        default: State
      RegTitle:
        default: Title
      RegZip:
        default: Zip/Postal Code
      SSLCertificateARN:
        default: SSL Certificate ARN (Requires matching DNS name)
      SourceCIDR:
        default: Source CIDR for Access
      TableauServerAdminPassword:
        default: Tableau Server administrator password
      TableauServerAdminUser:
        default: Tableau Server administrator username
      TableauServerLicenseKey:
        default: Tableau Activation Key
      Username:
        default: Tableau Services Manager (TSM) administrator username

Parameters:
  AMIOS:
    AllowedValues:
      - Amazon-Linux-2
      - CentOS-7-HVM
      - Ubuntu-Server-16.04-LTS-HVM
      - Windows-Server-2012-R2
    Description: The Linux or Windows distribution for the AMI to be used for the EC2 instances
    Type: String
  AWSHostedZoneID:
    Description: DNS Zone ID to contain the cluster's DNS entry (blank = no DNS)
    Type: String
  AWSPublicFQDN:
    Description: Tableau Server portal will be reachable at this address (blank = no DNS)
    Type: String
  AcceptEULA:
    AllowedPattern: 'Yes'
    AllowedValues:
    - 'Yes'
    - 'No'
    Description: 'View the EULA at the Link: https://www.tableau.com/eula'
    Type: String
  IPAddress:
    Description: Provide an Elastic IP address (EIP) for the initial node (blank = no EIP)
    Type: String
  InstanceType:
    AllowedValues:
    - c5.4xlarge
    - c5d.4xlarge
    - c4.4xlarge
    - m4.4xlarge
    - m5.4xlarge
    - r5d.4xlarge
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m5.4xlarge
    Description: Amazon EC2 instance type
    Type: String
  KeyPairName:
    AllowedPattern: ".+"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  Password:
    Description: Tableau Services Manager (TSM) administrator password
    Type: String
    NoEcho: true
    AllowedPattern: "^(?=[a-zA-Z0-9#@$?!]{8,}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9]).*"
    MinLength: '8'
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets in your VPC
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets in your VPC
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-tableau-server/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RegCity:
    Description: City
    MinLength: 1
    Type: String
  RegCompany:
    Description: Company
    MinLength: 1
    Type: String
  RegCountry:
    Description: Country
    MinLength: 1
    Type: String
  RegDepartment:
    Description: Department
    MinLength: 1
    Type: String
  RegEmail:
    Description: Email
    MinLength: 1
    Type: String
  RegFirstName:
    Description: First Name
    MinLength: 1
    Type: String
  RegIndustry:
    Description: Industry
    MinLength: 1
    Type: String
  RegLastName:
    Description: Last Name
    MinLength: 1
    Type: String
  RegPhone:
    Description: Phone
    MinLength: 1
    Type: String
  RegState:
    Description: State
    MinLength: 1
    Type: String
  RegTitle:
    Description: Title
    MinLength: 1
    Type: String
  RegZip:
    Description: ZIP/Postal Code
    MinLength: 1
    Type: String
  SSLCertificateARN:
    Default: ''
    Description: The Amazon Resource Name for the existing SSL cert you wish to use for the load balancer; empty for none
    Type: String
  SourceCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: IP address/range to allow access from
    Type: String
  TableauServerAdminPassword:
    Description: The password of the initial administrator for Tableau Server
    MinLength: 1
    NoEcho: true
    Type: String
  TableauServerAdminUser:
    Description: The name of the initial administrator for Tableau Server
    MinLength: 1
    Type: String
  TableauServerLicenseKey:
    Description: License Key
    MinLength: 1
    Type: String
  Username:
    Description: Tableau Services Manager (TSM) administrator username (cannot be
      Administrator)
    Type: String
    AllowedPattern: "[A-Za-z0-9]+"
    MaxLength: '30'
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Amazon VPC ID
Conditions:
  HealthcareVersion: !Equals [ !Ref HealthcareVersion, "YES" ]
  IsMultiNode: !Equals [ !Ref SingleOrMultiNode, "Multi" ]
  IsSingleNode: !Equals [ !Ref SingleOrMultiNode, "Single" ]

Mappings:
  AWSAMIRegionMap:
    AMI:
      CENTOS7HVM: CentOS Linux 7 x86_64 HVM EBS ENA 1804_2-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-55a2322a.4
      US1604HVM: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180509
      WS2012R2: Windows_Server-2012-R2_RTM-English-64Bit-Base-2018.05.09
    ap-northeast-1:
      CENTOS7HVM: ami-3185744e
      US1604HVM: ami-cbb259b4
      WS2012R2: ami-9be803e4
    ap-northeast-2:
      CENTOS7HVM: ami-46963e28
      US1604HVM: ami-191cb577
      WS2012R2: ami-4a1eb724
    ap-south-1:
      CENTOS7HVM: ami-48301d27
      US1604HVM: ami-ff80a390
      WS2012R2: ami-2289aa4d
    ap-southeast-1:
      CENTOS7HVM: ami-da6151a6
      US1604HVM: ami-d62014aa
      WS2012R2: ami-14a89d68
    ap-southeast-2:
      CENTOS7HVM: ami-0d13c26f
      US1604HVM: ami-9176a1f3
      WS2012R2: ami-c971a6ab
    ca-central-1:
      CENTOS7HVM: ami-456aea21
      US1604HVM: ami-fe93139a
      WS2012R2: ami-4a97172e
    eu-central-1:
      CENTOS7HVM: ami-9a183671
      US1604HVM: ami-e3381508
      WS2012R2: ami-3c0f22d7
    eu-west-1:
      CENTOS7HVM: ami-4c457735
      US1604HVM: ami-895e69f0
      WS2012R2: ami-4390a43a
    eu-west-2:
      CENTOS7HVM: ami-4726cb20
      US1604HVM: ami-3d43a15a
      WS2012R2: ami-e940a28e
    sa-east-1:
      CENTOS7HVM: ami-c2e6baae
      US1604HVM: ami-05dd8069
      WS2012R2: ami-b9df82d5
    us-east-1:
      CENTOS7HVM: ami-d5bf2caa
      US1604HVM: ami-5c66ea23
      WS2012R2: ami-2a9a1655
    us-east-2:
      CENTOS7HVM: ami-77724e12
      US1604HVM: ami-cf172aaa
      WS2012R2: ami-ee112c8b
    us-west-1:
      CENTOS7HVM: ami-3b89905b
      US1604HVM: ami-44273924
      WS2012R2: ami-63253b03
    us-west-2:
      CENTOS7HVM: ami-5490ed2c
      US1604HVM: ami-b5ed9ccd
      WS2012R2: ami-bbd6a7c3
  AWSAMINameMap:
    CentOS-7-HVM:
      Code: CENTOS7HVM
    Ubuntu-Server-16.04-LTS-HVM:
      Code: US1604HVM
    Windows-Server-2012-R2: 
      Code: WS2012R2

Resources:
  # First, encrypt the AMI root volume
  EncryptAmiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/encrypt-ami.yaml
      Parameters:
        AmiId: !FindInMap [ AWSAMIRegionMap , !Ref "AWS::Region", !FindInMap [ AWSAMINameMap, !Ref AMIOS, Code ] ]
        AmiRegion: !Ref "AWS::Region"
        SubnetId: !Select [ 0, !Ref PrivateSubnetIds ]

  # Next, create the Elb in a public subnet
  Elb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
      - Key: access_logs.s3.enabled
        Value: true
      - Key: access_logs.s3.bucket
        Value: !Ref LogBucket
      - Key: access_logs.s3.prefix
        Value: tableau-elb-logs
      Scheme: internet-facing
      Subnets: !Ref PublicSubnetIds
      Type: application

  ElbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates: 
        - CertificateArn: !Ref SSLCertificateARN
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ElbTargetGroup
      LoadBalancerArn: !Ref Elb
      Port: 443
      Protocol: HTTPS

  ElbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 443
      Protocol: HTTPS
      VpcId: !Ref VpcId

  # Configure Instance Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH/RDP access and HTTPS from the load balancer only
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !If [ IsWindows, 3389, 22 ]
        ToPort: !If [ IsWindows, 3389, 22 ]
        CidrIp: !Ref BastionSecurityGroup
      - IpProtocol: tcp
        FromPort: 8850
        ToPort: 8850
        SourceSecurityGroupId: !Ref BastionSecurityGroup
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId: !Select [ 0, !GetAtt Elb.SecurityGroups ]
      VpcId: !Ref VpcId   

  TableauServerWindows:
    Type: AWS::CloudFormation::Stack
    Condition: IsWindows
    Properties:
      TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/tableau-single-server-windows.yaml
      Parameters:
        AcceptEULA: !Ref AcceptEULA
        ElbTargetGroup: !Ref ElbTargetGroup
        ImageId: !GetAtt EncryptedAmiId
        InstanceSecurityGroup: !Ref InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        KeyPairName: !Ref KeyPairName
        Password: !Ref Password
        RegCity: !Ref RegCity
        RegCompany: !Ref RegCompany
        RegCountry: !Ref RegCountry
        RegDepartment: !Ref RegDepartment
        RegEmail: !Ref RegEmail
        RegFirstName: !Ref RegFirstName
        RegIndustry: !Ref RegIndustry
        RegLastName: !Ref RegLastName
        RegPhone: !Ref RegPhone
        RegState: !Ref RegSTate
        RegTitle: !Ref RegTitle
        TableauServerAdminUser: !Ref TableauServerAdminUser
        TableauServerAdminPassword: !Ref TableauServerAdminPassword
        TableauServerLicenseKey: !Ref TableauServerLicenseKey
        Username: !Ref Username
        
 
Outputs:
    # To fill in