global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-tableau-server-healthcare
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-tableau-server-healthcaret1:
    parameter_input: quickstart-tableau-server-healthcare-example-params1.json
    template_file: quickstart-tableau-server-healthcare-example1.template
  quickstart-tableau-server-healthcaret2:
    parameter_input: quickstart-tableau-server-healthcare-example-params2.json
    template_file: quickstart-tableau-server-healthcare-example2.template
