global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-tableau-server-healthcare
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-tableau-server-healthcaret1:
    parameter_input: tableau-windows.json
    template_file: tableau-server-master.yaml
    regions:
      - us-east-1

